name: Thomas Leroy
absolute_url: https://thole.fr
email: thomas.leroy.mp@gmail.com
twitter: https://twitter.com/P4zuu

permalink: /blog/:year/:month/:day/:title
github_username: LthomasMP
theme: jekyll-theme-minimal
